### ISSUE TITLE
Not rendering correctly when canceling skyboxes

### ISSUE THREAD

**Issue by jadevaky** [Popov72/FluidRendering#1]
// this._setEnvironment();

![lQLPJxbbVWf6lcfNATrNAWuw7EslUb_07xYDaGwplgCbAA_363_314](https://user-images.githubusercontent.com/115533497/200790577-2de98903-ad29-43b9-b943-81068a8d6053.png)

**Comment by Popov72** [comment]
The fluid renderer has now been added to Babylon.js, so you should ask your question in the [forum](https://forum.babylonjs.com/).

Thanks!
